name: lc0
description: An Lc0 Chess Engine for Flutter.
version: 1.4.0
repository: https://github.com/lichess-org/dart-lc0.git
homepage: https://github.com/lichess-org/dart-lc0.git

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lc0
        pluginClass: Lc0Plugin
      ios:
        pluginClass: Lc0Plugin
